Update tests
- In PHPUnit 10+, docblock annotations like `@dataProvider` are deprecated/removed
- Data providers must be static

Error: https://fundraising-ci.wikimedia.de/repos/7/pipeline/656/3